### ISSUE TITLE
[feat] Connect to Azure Database for PostgreSQL using Azure Workload Identity

### ISSUE THREAD

**Issue by schwichti** [dspace-group/simphera-reference-architecture-azure#84]
Support connecting to Azure Database for PostgreSQL using [Azure Workload Identities](https://azure.github.io/azure-workload-identity/docs/).

There is documentation on how to [Deploy and configure workload identity on an Azure Kubernetes Service (AKS) cluster](https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster) and [Connect with Managed Identity to Azure Database for PostgreSQL](https://learn.microsoft.com/en-us/azure/postgresql/single-server/how-to-connect-with-managed-identity). The idea is to limit the access of a single pod (pgbouncer) to grant access to the Azure Database for PostgreSQL through Azure Workload Identities.

The following has been tried without success:
- Open portal.azure.com
- Go to your Azure Database for PostgreSQL
- In the menu bar open *Active Directory admin*
- Add an Active Directory admin
- Run `az account get-access-token --resource https://ossrdbms-aad.database.windows.net`
- Run `kubectl create namespace simphera`
- Run `kubectl run pgdump -ti -n simphera --image postgres --kubeconfig ./your.kubeconfig -- bash`
- Inside the pod `pgdump` run `export PGPASSWORD=eyJ0eXAiOiJ...` to set the access token you got earlier as PGPASSWORD.
- Connect to the database as Active Directory admin `psql "host=<servername>.postgres.database.azure.com user=<username>@<servername> dbname=postgres sslmode=require"`
- Run the following SQL commands:
```sql
SET aad_validate_oids_in_tenant = off;
CREATE ROLE postgresql WITH LOGIN PASSWORD '<client_id>' IN ROLE azure_ad_user;
GRANT ALL PRIVILEGES ON DATABASE simphera TO postgresql;
```
- Run from your administration PC
```powershell
$KUBECONF = "./your.kubeconfig"

kubectl create namespace simphera --kubeconfig $KUBECONF

$RESOURCE_GROUP="<name of AKS resource group>"
$LOCATION="westeurope"
$SERVICE_ACCOUNT_NAMESPACE="simphera"
$SERVICE_ACCOUNT_NAME="postgresql"
$USER_ASSIGNED_IDENTITY_NAME="<any name of your choice>"
$FEDERATED_IDENTITY_CREDENTIAL_NAME="<any name of your choice>"

$AKS_OIDC_ISSUER=az aks show -n <aks-name> -g $RESOURCE_GROUP --query "oidcIssuerProfile.issuerUrl" -otsv

az identity create --name $USER_ASSIGNED_IDENTITY_NAME --resource-group $RESOURCE_GROUP --location $LOCATION --subscription $SUBSCRIPTION
$USER_ASSIGNED_CLIENT_ID =az identity show --resource-group $RESOURCE_GROUP --name $USER_ASSIGNED_IDENTITY_NAME --query 'clientId' -otsv

$serviceaccount = @"
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: $USER_ASSIGNED_CLIENT_ID
  labels:
    azure.workload.identity/use: "true"
  name: $SERVICE_ACCOUNT_NAME
  namespace: $SERVICE_ACCOUNT_NAMESPACE
"@

$serviceaccount | kubectl apply --kubeconfig $KUBECONF -f -
az identity federated-credential create --name $FEDERATED_IDENTITY_CREDENTIAL_NAME --identity-name $USER_ASSIGNED_IDENTITY_NAME --resource-group $RESOURCE_GROUP --issuer $AKS_OIDC_ISSUER --subject "system:serviceaccount:${SERVICE_ACCOUNT_NAMESPACE}:${SERVICE_ACCOUNT_NAME}" --audience api://AzureADTokenExchange

$pod = @"
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: simphera
  labels:
    azure.workload.identity/use: "true"  
spec:
  serviceAccountName: postgresql
  containers:
  - name: postgres
    image: postgres
    args:
    - bash
    stdin: true
    stdinOnce: true
    tty: true    
"@

$pod | kubectl apply --kubeconfig $KUBECONF -f -
```
- Inside the pod `postgres` run the following command
```bash
apt-get update
apt-get install wget jq
wget -O response.json --header='Metadata: true' 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fossrdbms-aad.database.windows.net&client_id=<client_id>'
```

Then I get the response:
```
Connecting to 169.254.169.254:80... connected.
HTTP request sent, awaiting response... 400 Bad Request
2023-04-18 22:01:59 ERROR 400: Bad Request.
```

We decided to stop investigation here and continue later.
Here are some references to keep track on the issue: 
- https://github.com/MicrosoftDocs/azure-docs/issues/108443
- https://github.com/Azure/azure-workload-identity/discussions/855

**Comment by slzmruepp** [comment]
We also need this feature. I was under the assumption this would work like all other managed identity. What is the issue here, any root cause?

**Comment by manojh1** [comment]
Even i am stuck in the same senario as i want to connect to postgres DB through workload managed identity.....
BTW did you found any solution for this.

**Comment by schwichti** [comment]
We decided not to use Azure Workload Identities so far.

You can try the solution proposed here: https://github.com/Azure/azure-workload-identity/discussions/855#discussioncomment-5724402
